`default_nettype none

// Auto-generated by scripts/gen_secded.py — do not edit
// (265, 256) Hamming code parity calculator
// 9 check bits at positions 1,2,4,8,16,32,64,128,256

module secded_parity (
    input  wire [255:0] data,
    output wire [8:0]   check
);

    // Check bit 0 (position 1): covers 132 data bits
    localparam [255:0] MASK_0 = 256'haad5555555555555555555555555555555aaaaaaaaaaaaaaab55555556aaad5b;
    assign check[0] = ^(data & MASK_0);

    // Check bit 1 (position 2): covers 131 data bits
    localparam [255:0] MASK_1 = 256'h3366666666666666666666666666666666cccccccccccccccd9999999b33366d;
    assign check[1] = ^(data & MASK_1);

    // Check bit 2 (position 4): covers 131 data bits
    localparam [255:0] MASK_2 = 256'h3c78787878787878787878787878787878f0f0f0f0f0f0f0f1e1e1e1e3c3c78e;
    assign check[2] = ^(data & MASK_2);

    // Check bit 3 (position 8): covers 129 data bits
    localparam [255:0] MASK_3 = 256'hc07f807f807f807f807f807f807f807f80ff00ff00ff00ff01fe01fe03fc07f0;
    assign check[3] = ^(data & MASK_3);

    // Check bit 4 (position 16): covers 127 data bits
    localparam [255:0] MASK_4 = 256'h007fff80007fff80007fff80007fff8000ffff0000ffff0001fffe0003fff800;
    assign check[4] = ^(data & MASK_4);

    // Check bit 5 (position 32): covers 127 data bits
    localparam [255:0] MASK_5 = 256'h007fffffff800000007fffffff80000000ffffffff00000001fffffffc000000;
    assign check[5] = ^(data & MASK_5);

    // Check bit 6 (position 64): covers 127 data bits
    localparam [255:0] MASK_6 = 256'h007fffffffffffffff8000000000000000fffffffffffffffe00000000000000;
    assign check[6] = ^(data & MASK_6);

    // Check bit 7 (position 128): covers 127 data bits
    localparam [255:0] MASK_7 = 256'h007fffffffffffffffffffffffffffffff000000000000000000000000000000;
    assign check[7] = ^(data & MASK_7);

    // Check bit 8 (position 256): covers 9 data bits
    localparam [255:0] MASK_8 = 256'hff80000000000000000000000000000000000000000000000000000000000000;
    assign check[8] = ^(data & MASK_8);

endmodule
